version: '3.8'

services:
  backend:
    volumes:
      - ../../backend/src:/app/src
    environment:
      SPRING_PROFILES_ACTIVE: local

  ai-server:
    volumes:
      - ../../ai-server/app:/app/app
      - ../../ai-server/data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
