spring.application.name=GenMark-AI
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Multipart / File upload config
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Upload directory location
file.upload-dir=uploads
