server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/genmark_db?useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:genmark_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:genmark_pass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ai.server.url=${AI_SERVER_URL:http://localhost:8000}
